-- ============================================================
-- VERTEX SUPPLY CHAIN PERFORMANCE ANALYSIS
-- SUPPLIER ANALYSIS
-- ============================================================


-- 1. TOP 5 PROFITABLE SUPPLIERS

SELECT
SUPPLIER_NAME,
NET_PROFIT,
RANKINGS
FROM
(
    SELECT
    SUPPLIER_NAME,
    SUM(NET_REVENUE) -
    SUM(INVENTORY_COST) -
    SUM(TOTAL_TRANSPORT_COST) AS NET_PROFIT,

    DENSE_RANK() OVER
    (
        ORDER BY
        SUM(NET_REVENUE) -
        SUM(INVENTORY_COST) -
        SUM(TOTAL_TRANSPORT_COST)
        DESC
    ) AS RANKINGS

    FROM
    (
        SELECT
        SUPPLIER_NAME,
        SUM(QUANTITY_RECEIVED) AS TOTAL_UNITS,
        SUM(QUANTITY_DAMAGED) AS DAMAGED_UNITS,
        SUM(QUANTITY_RECEIVED) -
        SUM(QUANTITY_DAMAGED) AS NET_UNITS,
        SELLING_PRICE,
        UNIT_COST,

        (
            SUM(QUANTITY_RECEIVED) * UNIT_COST
        ) AS INVENTORY_COST,

        (
            (
                SUM(QUANTITY_RECEIVED) -
                SUM(QUANTITY_DAMAGED)
            ) * SELLING_PRICE
        ) AS NET_REVENUE,

        SUM(TRANSPORT_COST) AS TOTAL_TRANSPORT_COST

        FROM PRODUCTS
        JOIN SUPPLIERS
        ON PRODUCTS.SUPPLIER_ID = SUPPLIERS.SUPPLIER_ID

        JOIN SHIPMENTS
        ON PRODUCTS.PRODUCT_ID = SHIPMENTS.PRODUCT_ID

        GROUP BY
        SUPPLIER_NAME,
        SELLING_PRICE,
        UNIT_COST
    ) AS SUBQUERY

    GROUP BY
    SUPPLIER_NAME
) AS PROFITS

WHERE RANKINGS <= 5;


-- 2. LOSS-MAKING SUPPLIERS

SELECT
SUPPLIER_NAME,
SUM(NET_REVENUE) -
SUM(INVENTORY_COST) -
SUM(TOTAL_TRANSPORT_COST) AS NET_PROFIT,

DENSE_RANK() OVER
(
    ORDER BY
    SUM(NET_REVENUE) -
    SUM(INVENTORY_COST) -
    SUM(TOTAL_TRANSPORT_COST)
    DESC
) AS RANKINGS

FROM
(
    SELECT
    SUPPLIER_NAME,
    SUM(QUANTITY_RECEIVED) AS TOTAL_UNITS,
    SUM(QUANTITY_DAMAGED) AS DAMAGED_UNITS,
    SUM(QUANTITY_RECEIVED) -
    SUM(QUANTITY_DAMAGED) AS NET_UNITS,
    SELLING_PRICE,
    UNIT_COST,

    (
        SUM(QUANTITY_RECEIVED) * UNIT_COST
    ) AS INVENTORY_COST,

    (
        (
            SUM(QUANTITY_RECEIVED) -
            SUM(QUANTITY_DAMAGED)
        ) * SELLING_PRICE
    ) AS NET_REVENUE,

    SUM(TRANSPORT_COST) AS TOTAL_TRANSPORT_COST

    FROM PRODUCTS
    JOIN SUPPLIERS
    ON PRODUCTS.SUPPLIER_ID = SUPPLIERS.SUPPLIER_ID

    JOIN SHIPMENTS
    ON PRODUCTS.PRODUCT_ID = SHIPMENTS.PRODUCT_ID

    GROUP BY
    SUPPLIER_NAME,
    SELLING_PRICE,
    UNIT_COST
) AS SUBQUERY

GROUP BY
SUPPLIER_NAME

HAVING NET_PROFIT <= 0;


-- 3. SUPPLIERS WITH THE MOST DAMAGED UNITS

SELECT
SUPPLIER_NAME,
SUM(QUANTITY_DAMAGED) AS DAMAGED_UNITS
FROM PRODUCTS
JOIN SUPPLIERS
ON PRODUCTS.SUPPLIER_ID = SUPPLIERS.SUPPLIER_ID
JOIN SHIPMENTS
ON PRODUCTS.PRODUCT_ID = SHIPMENTS.PRODUCT_ID
GROUP BY
SUPPLIER_NAME
ORDER BY
DAMAGED_UNITS DESC;


-- 4. SUPPLIERS WITH THE HIGHEST TRANSPORTATION COST

SELECT
SUPPLIER_NAME,
SUM(TRANSPORT_COST) AS TOTAL_TRANSPORT_COST
FROM PRODUCTS
JOIN SUPPLIERS
ON PRODUCTS.SUPPLIER_ID = SUPPLIERS.SUPPLIER_ID
JOIN SHIPMENTS
ON PRODUCTS.PRODUCT_ID = SHIPMENTS.PRODUCT_ID
GROUP BY
SUPPLIER_NAME
ORDER BY
TOTAL_TRANSPORT_COST DESC;


-- 5. SUPPLIER PERFORMANCE OVER TIME

SELECT
SUPPLIER_NAME,
MONTHS,
SUM(NET_REVENUE) OVER
(
    PARTITION BY SUPPLIER_NAME
    ORDER BY MONTHS
) AS NET_REVENUE

FROM
(
    SELECT
    SUPPLIER_NAME,
    MONTHS,
    SUM(NET_UNITS * SELLING_PRICE) AS NET_REVENUE

    FROM
    (
        SELECT
        SUPPLIER_NAME,
        PRODUCT_NAME,
        MONTHNAME(SHIPMENT_DATE) AS MONTHS,
        SUM(QUANTITY_RECEIVED) AS TOTAL_UNITS,
        SUM(QUANTITY_DAMAGED) AS DAMAGED_UNITS,
        SUM(QUANTITY_RECEIVED) -
        SUM(QUANTITY_DAMAGED) AS NET_UNITS,
        SELLING_PRICE,
        UNIT_COST

        FROM SUPPLIERS

        JOIN PRODUCTS
        ON PRODUCTS.SUPPLIER_ID = SUPPLIERS.SUPPLIER_ID

        JOIN SHIPMENTS
        ON SHIPMENTS.PRODUCT_ID = PRODUCTS.PRODUCT_ID

        GROUP BY
        SUPPLIER_NAME,
        PRODUCT_NAME,
        MONTHS,
        SELLING_PRICE,
        UNIT_COST
    ) AS SUBQUERY

    GROUP BY
    SUPPLIER_NAME,
    MONTHS
) AS SUBS;


-- 6. TOP 5 SUPPLIERS BY RATING

SELECT
SUPPLIER_NAME,
SUPPLIER_RATING,
RANKING
FROM
(
    SELECT
    SUPPLIER_NAME,
    SUPPLIER_RATING,

    DENSE_RANK() OVER
    (
        ORDER BY SUPPLIER_RATING DESC
    ) AS RANKING

    FROM SUPPLIERS
) AS SUPPLIER_RANKINGS

WHERE RANKING <= 5;


-- 7. TOP 5 SUPPLIERS BY LEAD TIME

SELECT
SUPPLIER_NAME,
LEAD_TIME_DAYS,
RANKINGS
FROM
(
    SELECT
    SUPPLIER_NAME,
    LEAD_TIME_DAYS,

    DENSE_RANK() OVER
    (
        ORDER BY LEAD_TIME_DAYS
    ) AS RANKINGS

    FROM SUPPLIERS
) AS SUPPLIER_RANKINGS

WHERE RANKINGS <= 5;
